<Project>
  <!-- 配布するプロジェクトだけに共通の公開情報を設定します。 -->
  <PropertyGroup>
    <Version>0.4.0</Version>
    <Authors>HrmsTrsmgs</Authors>
    <PackageProjectUrl>https://github.com/HrmsTrsmgs/document-as-data</PackageProjectUrl>
    <RepositoryUrl>https://github.com/HrmsTrsmgs/document-as-data</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>
</Project>
